Blog: Postgres Cafe Episode 1 - pgroll
xataio/mdx-blog pull request #343
Opened 2024-12-13 14:49 UTC by CezzaineZ

## Summary
https://docs.google.com/document/d/1QrA2XzU1iMaPcFgT0zmPG-Kb_Qi_FamO0THRpbmu1Vw/edit?tab=t.0

### Blog Release Checklist

- \[ ] Release on: \<mm/dd/yy>
- \[ ] Published on dev.to (connected to Xata org)
- \[ ] OG image included
- \[ ] Social media is scheduled for this post

2024-12-13 16:06 UTC, CezzaineZ commented on postgres-cafe-pgroll.mdx
> +<ArticleVideo platform="youtube" src="https://www.youtube.com/embed/WwaJd2c9whM?si=JQOz2YTr-VH6ZudG" />
```suggestion
<ArticleVideo platform="youtube" src="https://www.youtube.com/embed/1j07dnd1nSY?si=LBPoDKT98RAn7KFs" />
```

2024-12-13 16:20 UTC, alexfrancoeur approved these changes
LGTM

2024-12-13 18:08 UTC, gulcin requested changes

2024-12-13 18:08 UTC, gulcin commented on postgres-cafe-pgroll.mdx
> +
"pgroll provides a practical solution to the most pressing schema change challenges by enabling safe rollbacks, adjustable backfilling, and thorough testing, giving developer and DBA teams the confidence they need to implement database changes without downtime."

2024-12-13 18:16 UTC, gulcin commented
A great write-up! Thanks @CezzaineZ , suggested a few minor changes.

2024-12-16 09:39 UTC, CezzaineZ commented on postgres-cafe-pgroll.mdx
> +In this first episode, we explore [pgroll](https://pgroll.com/), our tool for achieving zero-downtime database schema changes, and the solutions it provides to common database migration challenges.
```suggestion
In this first episode, we explore [pgroll](https://pgroll.com/), our tool for achieving zero-downtime database schema changes, and the solutions it offers for overcoming common challenges in modifying database schemas.
```

2024-12-16 09:40 UTC, CezzaineZ commented on postgres-cafe-pgroll.mdx
> +Schema changes are often challenging, especially for production databases where downtime is not an option. In this episode, we discuss pgroll, a tool designed to tackle these migration pain points wi
```suggestion
Schema changes are often challenging, especially for production databases where downtime is not an option. In this episode, we discuss pgroll, a tool designed to tackle these challenges with an approach that prioritizes reliability and uptime. Here’s a look at what this episode covered:
```

2024-12-16 09:41 UTC, CezzaineZ commented on postgres-cafe-pgroll.mdx
> +- **Rollback complexity:** Rollbacks are often tricky and rarely tested, especially when schema changes can’t be easily undone. pgroll addresses this with a migration pattern that simplifies revertin
```suggestion
- **Rollback complexity:** Rollbacks are often tricky and rarely tested, especially when schema changes can’t be easily undone. pgroll addresses this with a pattern that simplifies reverting changes without application downtime.
```

2024-12-16 09:42 UTC, CezzaineZ commented on postgres-cafe-pgroll.mdx
> +- Offering **schema version views** so applications can connect to the specific schema version they need, enabling zero-downtime migrations.
```suggestion
- Offering **schema version views** so applications can connect to the specific schema version they need, enabling zero-downtime alterations.
```

2024-12-16 09:43 UTC, CezzaineZ commented on postgres-cafe-pgroll.mdx
> +pgroll provides a practical solution to the most pressing migration challenges, reducing downtime and making complex changes more manageable for developers.
```suggestion
pgroll provides a practical solution to the most pressing schema change challenges, by enabling safe rollbacks, adjustable backfilling, and thorough testing, giving developer and DBA teams the confidence they need to implement database changes without downtime.
```

2024-12-16 09:45 UTC, CezzaineZ commented on postgres-cafe-pgroll.mdx
> +This is just the start of Postgres Cafe! [Subscribe to the playlist](https://www.youtube.com/playlist?list=PLf7KS0svgDP_zJmby3RMzzOVO45qLbruA) for future episodes that will feature more open-source t
```suggestion
This is just the start of Postgres Cafe! [Subscribe to the playlist](https://www.youtube.com/playlist?list=PLf7KS0svgDP_zJmby3RMzzOVO45qLbruA) for future episodes that will feature more open-source tools like [pgstream](https://xata.io/pgstream) for managing real-time data streaming, [StatsMgr](https://git.data-bene.io/cedric/statsmgr) for managing statistics in PostgreSQL, and more. Watch this space to learn how each tool can make working with Postgres smoother and more efficient.
```

2024-12-16 09:46 UTC, CezzaineZ commented on postgres-cafe-pgroll.mdx
> +The [expand-contract pattern](https://xata.io/blog/pgroll-expand-contract) is a safe and reliable approach for schema migrations. pgroll automates this multi-step process by:
```suggestion
The [expand-contract pattern](https://xata.io/blog/pgroll-expand-contract) is a safe and reliable approach for schema changes. pgroll automates this multi-step process by:
```

2024-12-18 12:06 UTC, gulcin approved these changes

2024-12-18 12:06 UTC, merged